import { defineConfig } from 'vite'
import vue from '@vitejs/plugin-vue'

// https://vitejs.dev/config/
export default defineConfig({
    plugins: [vue()], // to process SFC
    build: {
        lib: {
            entry: 'src/main.ts',
            name: 'inertia-table',
            formats: ['es'], // adding 'umd' requires globals set to every external module
            fileName: (format) => `inertia-table.${format}.js`,
        },
        rollupOptions: {
            // external modules won't be bundled into your library
            external: ['vue', '@inertiajs/vue3'], // not every external has a global
            output: {
                // disable warning on src/index.ts using both default and named export
                exports: 'named',
                // Provide global variables to use in the UMD build
                // for externalized deps (not useful if 'umd' is not in lib.formats)
                globals: {
                    vue: 'Vue',
                },
            },
        },
        emptyOutDir: false, // to retain the types folder generated by tsc
    },
})
